<?php

namespace App\Actions\Students;

use App\Actions\Identity\GenerateStudentCode;
use App\Enums\ProfileStatus;
use App\Enums\RoleName;
use App\Enums\UserStatus;
use App\Exceptions\ApiException;
use App\Models\CareerCompassLevel;
use App\Models\StudentProfile;
use App\Models\User;
use App\Support\ErrorCode;
use Illuminate\Support\Facades\DB;

class CreateStudent
{
    public function __construct(private readonly GenerateStudentCode $generateStudentCode) {}

    /**
     * @param  array{
     *     name: string,
     *     email: string,
     *     password: string,
     *     career_compass_level_id: string,
     *     class_grade?: int,
     *     phone: string,
     *     whatsapp_number?: string|null,
     *     academic_year?: int,
     *     guardian_name?: string|null,
     *     guardian_phone?: string|null
     * }  $input
     */
    public function execute(array $input): StudentProfile
    {
        if (array_key_exists('student_code', $input) && $input['student_code'] !== null) {
            throw new ApiException(
                ErrorCode::STUDENT_CODE_IMMUTABLE,
                'Student ID is generated by the server and cannot be supplied.',
                422,
            );
        }

        $level = CareerCompassLevel::query()->findOrFail($input['career_compass_level_id']);
        $grade = (int) ($input['class_grade'] ?? $level->class_from);

        if ($grade < $level->class_from || $grade > $level->class_to) {
            throw new ApiException(
                ErrorCode::VALIDATION_ERROR,
                "Class {$grade} is not valid for {$level->code}.",
                422,
                ['class_grade' => ["Must be between {$level->class_from} and {$level->class_to}."]],
            );
        }

        $academicYear = (int) ($input['academic_year'] ?? now()->year);

        return DB::transaction(function () use ($input, $level, $grade, $academicYear): StudentProfile {
            $user = User::query()->create([
                'name' => $input['name'],
                'email' => $input['email'],
                'password' => $input['password'],
                'status' => UserStatus::Active,
            ]);
            $user->assignRole(RoleName::Student->value);

            $code = $this->generateStudentCode->execute($level, $academicYear);

            return StudentProfile::query()->create([
                'user_id' => $user->id,
                'student_code' => $code,
                'career_compass_level_id' => $level->id,
                'class_grade' => $grade,
                'full_name' => $input['name'],
                'phone' => $input['phone'],
                'whatsapp_number' => $input['whatsapp_number'] ?? null,
                'guardian_name' => $input['guardian_name'] ?? null,
                'guardian_phone' => $input['guardian_phone'] ?? null,
                'status' => ProfileStatus::Active,
                'id_academic_year' => $academicYear,
            ]);
        });
    }
}
