<?php

namespace App\Actions\Students;

use App\Actions\Batches\AllocateBatchForStudent;
use App\Actions\Identity\GenerateStudentCode;
use App\Actions\Learning\StartStudentLevelJourney;
use App\Enums\ProfileStatus;
use App\Enums\RoleName;
use App\Enums\UserStatus;
use App\Exceptions\ApiException;
use App\Models\AcademicLevel;
use App\Models\CareerCompassLevel;
use App\Models\StudentProfile;
use App\Models\User;
use App\Support\ErrorCode;
use Illuminate\Support\Facades\DB;

class CreateStudent
{
    public function __construct(
        private readonly GenerateStudentCode $generateStudentCode,
        private readonly AllocateBatchForStudent $allocateBatchForStudent,
        private readonly StartStudentLevelJourney $startStudentLevelJourney,
    ) {}

    /**
     * @param  array{
     *     name: string,
     *     email: string,
     *     password: string,
     *     level_id?: string|null,
     *     career_compass_level_id?: string,
     *     class_grade?: int,
     *     phone: string,
     *     whatsapp_number?: string|null,
     *     address?: string|null,
     *     academic_year?: int,
     *     guardian_name?: string|null,
     *     guardian_phone?: string|null
     * }  $input
     */
    public function execute(array $input): StudentProfile
    {
        if (array_key_exists('student_code', $input) && $input['student_code'] !== null) {
            throw new ApiException(
                ErrorCode::STUDENT_CODE_IMMUTABLE,
                'Student ID is generated by the server and cannot be supplied.',
                422,
            );
        }

        if (! empty($input['career_compass_level_id'])) {
            $level = CareerCompassLevel::query()->findOrFail($input['career_compass_level_id']);
            $grade = (int) ($input['class_grade'] ?? $level->class_from);
        } elseif (isset($input['class_grade'])) {
            $grade = (int) $input['class_grade'];
            $level = CareerCompassLevel::query()
                ->where('class_from', '<=', $grade)
                ->where('class_to', '>=', $grade)
                ->firstOrFail();
        } else {
            throw new ApiException(
                ErrorCode::VALIDATION_ERROR,
                'Either class_grade or career_compass_level_id is required.',
                422,
            );
        }

        if ($grade < $level->class_from || $grade > $level->class_to) {
            throw new ApiException(
                ErrorCode::VALIDATION_ERROR,
                "Class {$grade} is not valid for {$level->code}.",
                422,
                ['class_grade' => ["Must be between {$level->class_from} and {$level->class_to}."]],
            );
        }

        $academicYear = (int) ($input['academic_year'] ?? now()->year);

        // Find AcademicLevel (default Level 1)
        $academicLevel = null;
        if (! empty($input['level_id'])) {
            $academicLevel = AcademicLevel::query()->find($input['level_id']);
        }
        if (! $academicLevel) {
            $academicLevel = AcademicLevel::query()->where('name', 'Level 1')->first();
        }

        return DB::transaction(function () use ($input, $level, $academicLevel, $grade, $academicYear): StudentProfile {
            $user = User::query()->create([
                'name' => $input['name'],
                'email' => $input['email'],
                'password' => $input['password'],
                'status' => UserStatus::Active,
            ]);
            $user->assignRole(RoleName::Student->value);

            $code = $this->generateStudentCode->execute($level, $academicYear);

            $profile = StudentProfile::query()->create([
                'user_id' => $user->id,
                'student_code' => $code,
                'level_id' => $academicLevel?->id,
                'career_compass_level_id' => $level->id,
                'class_grade' => $grade,
                'full_name' => $input['name'],
                'phone' => $input['phone'],
                'whatsapp_number' => $input['whatsapp_number'] ?? null,
                'address' => $input['address'] ?? null,
                'guardian_name' => $input['guardian_name'] ?? null,
                'guardian_phone' => $input['guardian_phone'] ?? null,
                'status' => ProfileStatus::Active,
                'id_academic_year' => $academicYear,
            ]);

            if ($academicLevel) {
                $actor = auth()->user() ?? $user;
                $this->allocateBatchForStudent->execute($academicLevel, $profile, $actor);
                $this->startStudentLevelJourney->execute($profile, $academicLevel);
            }

            return $profile;
        });
    }
}
