<?php

namespace App\Support;

final class ErrorCode
{
    public const UNAUTHENTICATED = 'UNAUTHENTICATED';

    public const FORBIDDEN = 'FORBIDDEN';

    public const NOT_FOUND = 'NOT_FOUND';

    public const VALIDATION_ERROR = 'VALIDATION_ERROR';

    public const CONFLICT = 'CONFLICT';

    public const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';

    public const SERVER_ERROR = 'SERVER_ERROR';

    public const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

    public const ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE';

    public const BATCH_FULL = 'BATCH_FULL';

    public const ASSIGNMENT_ACTIVE = 'ASSIGNMENT_ACTIVE';

    public const STUDENT_CODE_IMMUTABLE = 'STUDENT_CODE_IMMUTABLE';

    public const ASSESSMENT_NOT_READY = 'ASSESSMENT_NOT_READY';

    public const ASSESSMENT_NOT_ACTIVE = 'ASSESSMENT_NOT_ACTIVE';

    public const ASSESSMENT_LEVEL_MISMATCH = 'ASSESSMENT_LEVEL_MISMATCH';

    public const ASSESSMENT_ALREADY_SUBMITTED = 'ASSESSMENT_ALREADY_SUBMITTED';

    public const ASSESSMENT_INCOMPLETE = 'ASSESSMENT_INCOMPLETE';

    public const ASSESSMENT_LOCKED = 'ASSESSMENT_LOCKED';

    public const FEEDBACK_LOCKED = 'FEEDBACK_LOCKED';

    public const FEEDBACK_DUPLICATE = 'FEEDBACK_DUPLICATE';

    public const FEEDBACK_NOT_DUE = 'FEEDBACK_NOT_DUE';

    public const LEAVE_OVERLAPS_BOOKING = 'LEAVE_OVERLAPS_BOOKING';

    public const LEAVE_OVERLAPS_LEAVE = 'LEAVE_OVERLAPS_LEAVE';

    public const LEAVE_DATE_PASSED = 'LEAVE_DATE_PASSED';

    public const LEAVE_NOT_APPROVABLE = 'LEAVE_NOT_APPROVABLE';

    public const LEAVE_REASSIGNMENT_INCOMPLETE = 'LEAVE_REASSIGNMENT_INCOMPLETE';

    public const SLOT_UNAVAILABLE = 'SLOT_UNAVAILABLE';

    public const BOOKING_OVERLAP = 'BOOKING_OVERLAP';

    public const INTRODUCTION_REQUIRED = 'INTRODUCTION_REQUIRED';

    public const MASTER_CLASS_MONTHLY_LIMIT = 'MASTER_CLASS_MONTHLY_LIMIT';

    public const TEACHER_NOT_ELIGIBLE = 'TEACHER_NOT_ELIGIBLE';

    public const MEETING_CREATE_FAILED = 'MEETING_CREATE_FAILED';

    public const GOOGLE_NOT_CONNECTED = 'GOOGLE_NOT_CONNECTED';

    public const ATTEMPT_LIMIT = 'ATTEMPT_LIMIT';

    public const JOIN_TOO_EARLY = 'JOIN_TOO_EARLY';

    public const ATTENDANCE_REPORT_TOO_EARLY = 'ATTENDANCE_REPORT_TOO_EARLY';

    public const ATTENDANCE_REPORT_TOO_LATE = 'ATTENDANCE_REPORT_TOO_LATE';

    public const ATTENDANCE_REPORT_DUPLICATE = 'ATTENDANCE_REPORT_DUPLICATE';

    public const ATTENDANCE_REPORT_NOT_ALLOWED = 'ATTENDANCE_REPORT_NOT_ALLOWED';

    public const WHATSAPP_WINDOW = 'WHATSAPP_WINDOW';

    public const STUDENT_WHATSAPP_UNAVAILABLE = 'STUDENT_WHATSAPP_UNAVAILABLE';
}
